baseURL = ""
languageCode = "en-ca"
title = "XIX3D"
theme = "xix"
pluralizeListTitles = false


# Site Wide:

# Index/Home page stuff:

[params.index.hero]
    video = "images/backgroundvideo3.webm"
    title = "XIX"
    txt = "Real time 3D configurator"
    img = "images/xixlogowhite.png"

[params.index.design]

# Pricing Page Stuff
[params.pricing1]
    pricingTitle1 = "Free Membership"
    price1 = "Free Lifetime"
    description1 = "OMG WHO THIMKS ITS LOL"
    checklist = ["Includes the following features:",
"XIX 3D branding within software",
"Tech Support",
"10-point touch configurator ",
"VR compatible",
"Standard inventory of car models",
"On-Demand live renders (limit 100)",
"Special indoor enviornments"
]

[params.pricing2]
    pricingTitle2 = "BJ Plans"
    price2 = "1 BJ/day"
    description2 = "JayZ has some big lips"
    checklist = ["Customizable enviornments",
    "Personalized branding within software",
    "Tech Support",
    "10-point touch configurator ",
    "VR compatible",
    "Advanced customization options",
    "Advanced inventory of car models",
    "On-Demand live renders (limit 300)",
    "Special indoor + outdoor envionrments"
]

[params.pricing3]
    pricingTitle3 = "Choke me daddy"
    price3 = "$1000/month"
    description3 = "No really JayZ BJ's must be blessed"
    checklist = ["Tech Support",
"10-point touch configurator ",
"VR compatible",
"Ultimate customization options",
"Full inventory of car model",
"sOn-Demand live renders (no limit)",
"All envionrments",
"Ultimate customizatibilty and assets",
"Customizable enviornments",
"Personalized branding within software"
]


# Footer Text
[params.footer]
    copyright = "2018 | XIX"