baseURL = "https://example.org/"
languageCode = "en-ca"
title = "XIX3D"
theme = "xix"
pluralizeListTitles = false

[params]
# Site Wide:

# Index/Home page stuff:

[params.index.hero]
    video = "images/backgroundvideo3.webm"
    title = "XIX"
    txt = "Real time 3D configurator"
    img = "images/xixlogowhite.png"

[params.footer]
    copyright = "2018 | XIX"