baseURL = "https://example.org/"
languageCode = "en-ca"
title = "XIX3D"
theme = "xix"
pluralizeListTitles = false

[params]

# Index/Home page stuff:

[params.index.hero]
    video = "images/backgroundvideo2.webm"
    title = "XIX"
    txt = "VR tingz"

[params.footer]
    copyright = "2018 | XIX"